[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tungstenite = "0.27.0"
tokio = { version = "1.46.1", features = ["full"] }
chrono = "0.4.41"
