[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
protocol = { path = "../protocol" }
tokio = { version = "1.46.1", features = ["full"] }
tokio-tungstenite = { version = "0.27.0", features = ["native-tls"] }
serde_json = "1.0.141"
